export const REPORTS_DATA = {
  MASTER: {
    revenue: '$450,780',
    revenueGrowth: '+14.2%',
    patientsSeen: '12,345',
    patientsGrowth: '+9.8%',
    avgTicket: '$52.10',
    ticketGrowth: '+3.5%',
    revenueMonthly: [
      { month: 'Jan', val: 380000, height: '50%' },
      { month: 'Feb', val: 410000, height: '65%' },
      { month: 'Mar', val: 395000, height: '60%' },
      { month: 'Apr', val: 450000, height: '82%' },
      { month: 'May', val: 425000, height: '75%' },
      { month: 'Jun', val: 450780, height: '90%' },
    ],
    patientTrends: [
      { day: 'Mon', scheduled: 180, walkin: 45, hSched: '75%', hWalk: '18%' },
      { day: 'Tue', scheduled: 165, walkin: 50, hSched: '68%', hWalk: '20%' },
      { day: 'Wed', scheduled: 210, walkin: 35, hSched: '88%', hWalk: '14%' },
      { day: 'Thu', scheduled: 155, walkin: 60, hSched: '64%', hWalk: '24%' },
      { day: 'Fri', scheduled: 190, walkin: 30, hSched: '78%', hWalk: '12%' },
    ],
    inventoryBreakdown: [
      { label: 'Dispensed Rx', pct: 58, color: 'bg-primary-600', val: '3,200 units' },
      { label: 'Restocked Items', pct: 35, color: 'bg-emerald-500', val: '1,950 units' },
      { label: 'Expired / Discarded', pct: 7, color: 'bg-danger', val: '380 units' },
    ],
  },
  SUB_MASTER: {
    revenue: '$38,420',
    revenueGrowth: '+5.3%',
    patientsSeen: '840',
    patientsGrowth: '+12.4%',
    avgTicket: '$45.70',
    ticketGrowth: '+1.2%',
    revenueMonthly: [
      { month: 'Jan', val: 28000, height: '55%' },
      { month: 'Feb', val: 31000, height: '62%' },
      { month: 'Mar', val: 29500, height: '58%' },
      { month: 'Apr', val: 35000, height: '78%' },
      { month: 'May', val: 32000, height: '70%' },
      { month: 'Jun', val: 38420, height: '90%' },
    ],
    patientTrends: [
      { day: 'Mon', scheduled: 42, walkin: 12, hSched: '70%', hWalk: '20%' },
      { day: 'Tue', scheduled: 38, walkin: 15, hSched: '64%', hWalk: '25%' },
      { day: 'Wed', scheduled: 48, walkin: 10, hSched: '80%', hWalk: '16%' },
      { day: 'Thu', scheduled: 35, walkin: 18, hSched: '58%', hWalk: '30%' },
      { day: 'Fri', scheduled: 44, walkin: 8, hSched: '73%', hWalk: '13%' },
    ],
    inventoryBreakdown: [
      { label: 'Dispensed Rx', pct: 65, color: 'bg-primary-600', val: '450 units' },
      { label: 'Restocked Items', pct: 25, color: 'bg-emerald-500', val: '170 units' },
      { label: 'Expired / Discarded', pct: 10, color: 'bg-danger', val: '70 units' },
    ],
  },
  DOCTOR: {
    totalConsultations: '234',
    consultationsGrowth: '+18.5%',
    avgDuration: '16.8 min',
    durationGrowth: '-4.2% (Faster)',
    rxRate: '88.5%',
    rxRateGrowth: '+2.1%',
    consultationsMonthly: [
      { month: 'Jan', val: 180, height: '50%' },
      { month: 'Feb', val: 195, height: '58%' },
      { month: 'Mar', val: 202, height: '62%' },
      { month: 'Apr', val: 220, height: '72%' },
      { month: 'May', val: 215, height: '68%' },
      { month: 'Jun', val: 234, height: '90%' },
    ],
    diagnosisTrends: [
      { day: 'Mon', chronic: 15, acute: 5, hChronic: '75%', hAcute: '25%' },
      { day: 'Tue', chronic: 12, acute: 8, hChronic: '60%', hAcute: '40%' },
      { day: 'Wed', chronic: 18, acute: 4, hChronic: '90%', hAcute: '20%' },
      { day: 'Thu', chronic: 10, acute: 10, hChronic: '50%', hAcute: '50%' },
      { day: 'Fri', chronic: 14, acute: 3, hChronic: '70%', hAcute: '15%' },
    ],
    outcomesBreakdown: [
      { label: 'Improved / Stable', pct: 82, color: 'bg-primary-600', val: '192 patients' },
      { label: 'Referred to Specialist', pct: 12, color: 'bg-emerald-500', val: '28 patients' },
      { label: 'Readmitted', pct: 6, color: 'bg-danger', val: '14 patients' },
    ],
  },
  NURSE: {
    totalIntakes: '382',
    intakesGrowth: '+10.4%',
    vitalsSuccess: '99.2%',
    vitalsGrowth: '+0.5%',
    pendingReminders: '4',
    remindersGrowth: '-50% (Cleared)',
    intakesWeekly: [
      { month: 'Mon', val: 24, height: '60%' },
      { month: 'Tue', val: 28, height: '72%' },
      { month: 'Wed', val: 32, height: '85%' },
      { month: 'Thu', val: 22, height: '55%' },
      { month: 'Fri', val: 35, height: '90%' },
    ],
    screeningBreakdown: [
      { day: 'Mon', routine: 18, urgent: 6, hRoutine: '75%', hUrgent: '25%' },
      { day: 'Tue', routine: 20, urgent: 8, hRoutine: '80%', hUrgent: '32%' },
      { day: 'Wed', routine: 25, urgent: 7, hRoutine: '95%', hUrgent: '28%' },
      { day: 'Thu', routine: 17, urgent: 5, hRoutine: '70%', hUrgent: '20%' },
      { day: 'Fri', routine: 30, urgent: 5, hRoutine: '98%', hUrgent: '20%' },
    ],
    tasksProgress: [
      { label: 'Intakes Completed', pct: 88, color: 'bg-primary-600', val: '336 cases' },
      { label: 'Pending Documentation', pct: 9, color: 'bg-emerald-500', val: '34 cases' },
      { label: 'Missed Follow-ups', pct: 3, color: 'bg-danger', val: '12 cases' },
    ],
  },
  PHARMACIST: {
    dispensedRx: '1,420',
    dispensedGrowth: '+15.2%',
    lowStockResolved: '14 Items',
    resolvedGrowth: '9 Left in Queue',
    expiryDisposed: '2 items',
    expiryGrowth: '-60% waste',
    dispensationMonthly: [
      { month: 'Jan', val: 950, height: '50%' },
      { month: 'Feb', val: 1100, height: '62%' },
      { month: 'Mar', val: 1050, height: '58%' },
      { month: 'Apr', val: 1250, height: '75%' },
      { month: 'May', val: 1300, height: '80%' },
      { month: 'Jun', val: 1420, height: '90%' },
    ],
    dispensedCategories: [
      { day: 'Mon', prescription: 40, otc: 12, hPresc: '80%', hOtc: '24%' },
      { day: 'Tue', prescription: 35, otc: 15, hPresc: '70%', hOtc: '30%' },
      { day: 'Wed', prescription: 45, otc: 10, hPresc: '90%', hOtc: '20%' },
      { day: 'Thu', prescription: 30, otc: 18, hPresc: '60%', hOtc: '36%' },
      { day: 'Fri', prescription: 38, otc: 8, hPresc: '76%', hOtc: '16%' },
    ],
    stockDeltaSummary: [
      { label: 'Dispensed Stock', pct: 72, color: 'bg-primary-600', val: '1,022 units' },
      { label: 'Restocked/Received', pct: 23, color: 'bg-emerald-500', val: '326 units' },
      { label: 'Expiry Discards', pct: 5, color: 'bg-danger', val: '72 units' },
    ],
  },
  RECEPTIONIST: {
    checkedIn: '640',
    checkedInGrowth: '+11.5%',
    avgWait: '11.8 min',
    waitGrowth: '-14% (Optimized)',
    cancellationRate: '4.2%',
    cancelGrowth: '-1.5% (Good)',
    checkinsMonthly: [
      { month: 'Jan', val: 420, height: '50%' },
      { month: 'Feb', val: 480, height: '62%' },
      { month: 'Mar', val: 510, height: '68%' },
      { month: 'Apr', val: 590, height: '82%' },
      { month: 'May', val: 570, height: '78%' },
      { month: 'Jun', val: 640, height: '90%' },
    ],
    patientFlowType: [
      { day: 'Mon', scheduled: 32, walkin: 14, hSched: '80%', hWalk: '35%' },
      { day: 'Tue', scheduled: 28, walkin: 16, hSched: '70%', hWalk: '40%' },
      { day: 'Wed', scheduled: 36, walkin: 12, hSched: '90%', hWalk: '30%' },
      { day: 'Thu', scheduled: 25, walkin: 20, hSched: '62%', hWalk: '50%' },
      { day: 'Fri', scheduled: 30, walkin: 8, hSched: '75%', hWalk: '20%' },
    ],
    flowCompleteness: [
      { label: 'Fully Intake Processed', pct: 85, color: 'bg-primary-600', val: '544 patients' },
      { label: 'Pending Dues Ledger', pct: 11, color: 'bg-emerald-500', val: '70 patients' },
      { label: 'No-Show / Cancelled', pct: 4, color: 'bg-danger', val: '26 patients' },
    ],
  },
};
